# Generated by Django 4.1.2 on 2024-06-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_apoderado', models.AutoField(db_column='idApoderado', primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='gestion_viajes.genero')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_apoderado',
            field=models.ForeignKey(db_column='idApoderado', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_viajes.apoderado'),
        ),
    ]
