# Generated by Django 4.1.2 on 2024-07-08 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0002_apoderado_alumno_id_apoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(db_column='idDestino', primary_key=True, serialize=False)),
                ('nombre_destino', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(db_column='idProveedor', primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=30)),
                ('email_proveedor', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tiposervicio', models.AutoField(db_column='idTipoServicio', primary_key=True, serialize=False)),
                ('descripcion_tiposervicio', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_apoderado',
            field=models.ForeignKey(db_column='idApoderado', on_delete=django.db.models.deletion.CASCADE, to='gestion_viajes.apoderado'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('descripcion_servicio', models.CharField(max_length=50)),
                ('precio_servicio', models.IntegerField()),
                ('id_destino', models.ForeignKey(db_column='idDestino', on_delete=django.db.models.deletion.CASCADE, to='gestion_viajes.destino')),
                ('id_proveedor', models.ForeignKey(db_column='idProveedor', on_delete=django.db.models.deletion.CASCADE, to='gestion_viajes.proveedor')),
                ('id_tiposervicio', models.ForeignKey(db_column='idTipoServicio', on_delete=django.db.models.deletion.CASCADE, to='gestion_viajes.tiposervicio')),
            ],
        ),
    ]
