# Generated by Django 4.1.2 on 2024-07-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0003_destino_proveedor_tiposervicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
